import { config } from '../config'

/**
 * The tuning panel. (spec 5.4, step 7)
 *
 * Generated by walking the config object rather than hand-written control by
 * control. That matters more than it sounds: a hand-built panel means every
 * new tuning value needs a second edit over here to become adjustable, and
 * within a month half the config isn't in the panel and nobody trusts it.
 * Walking the object means anything added to config.ts is adjustable the
 * moment it exists, forever, for free.
 *
 * Everything in the game reads config live, so edits apply on the next frame.
 * The exceptions are values consumed once at startup or at the birth of a run;
 * those are labelled rather than silently doing nothing.
 */

/** Read once at load or at createWorld, so editing them mid-run does nothing. */
const NEEDS_RESTART = new Set([
  'world.seed',
  'character.moveSpeed',
  'character.maxHp',
  'character.radius',
  'character.startingWeaponIds',
  'influence.cellSize',
  'influence.gridRadiusCells',
  'enemies.gridCellSize',
  'pickups.merge.radius',
  'shop.distanceFromStart',
])

/** Where the automatic range is a poor fit. */
const RANGE_OVERRIDES: Record<string, [number, number]> = {
  'render.yScale': [0.3, 1],
  'render.visibleWorldHeight': [400, 3000],
  'render.cameraFollowRate': [1, 20],
  'influence.updateHz': [5, 60],
  'influence.flow.decay': [0.8, 0.999],
  'influence.flow.minPassability': [0, 0.5],
  'influence.flow.sweeps': [1, 8],
  'movement.sampleDirections': [8, 48],
  'draft.choices': [1, 6],
  'pickups.merge.count': [2, 10],
  'spawn.margin': [1.42, 3],
}

const FALLOFF_CHOICES = ['sharp', 'linear', 'smooth', 'wide']

const STYLES = `
.dbg-toggle {
  position: fixed; left: 14px; top: 14px; z-index: 30;
  padding: 6px 12px; border: 1px solid #3a4a58; border-radius: 5px;
  background: #141a20cc; color: #9fb3c2; cursor: pointer;
  font: 12px ui-monospace, Consolas, monospace;
}
.dbg-toggle:hover { color: #e8c468; border-color: #e8c468; }

.dbg-panel {
  position: fixed; left: 0; top: 0; bottom: 0; z-index: 29;
  width: 340px; overflow-y: auto; padding: 52px 14px 20px;
  background: #0d1218f2; border-right: 1px solid #2a3540;
  font: 12px ui-monospace, Consolas, monospace; color: #9fb3c2;
}
.dbg-panel[hidden] { display: none; }
.dbg-panel details { margin-bottom: 6px; border: 1px solid #222c36; border-radius: 5px; }
.dbg-panel summary {
  cursor: pointer; padding: 7px 10px; color: #e8c468;
  background: #141b23; border-radius: 4px; user-select: none;
}
.dbg-panel details[open] > summary { border-bottom: 1px solid #222c36; }
.dbg-body { padding: 8px 10px; display: flex; flex-direction: column; gap: 9px; }

.dbg-row { display: flex; flex-direction: column; gap: 3px; }
.dbg-label { display: flex; justify-content: space-between; gap: 8px; }
.dbg-name { color: #8fa3b2; }
.dbg-name.restart::after { content: ' (restart)'; color: #7a5f3a; }
.dbg-value { color: #e8e8e8; }
.dbg-row input[type=range] { width: 100%; accent-color: #e8c468; }
.dbg-row input[type=text], .dbg-row select {
  background: #0a0e13; color: #cfe0ec; border: 1px solid #2a3540;
  border-radius: 4px; padding: 4px 6px; font: inherit; width: 100%;
}
.dbg-row input[type=color] { width: 100%; height: 22px; background: none; border: none; }
.dbg-actions { display: flex; gap: 8px; margin-bottom: 12px; }
.dbg-actions button {
  flex: 1; padding: 6px; border: 1px solid #3a4a58; border-radius: 4px;
  background: #141b23; color: #9fb3c2; cursor: pointer; font: inherit;
}
.dbg-actions button:hover { border-color: #e8c468; color: #e8c468; }
`

type Bag = Record<string, unknown>

/** A step that keeps the slider usable across values from 0.01 to 3000. */
function stepFor(value: number, min: number, max: number): number {
  const span = Math.abs(max - min) || Math.abs(value) || 1
  const raw = span / 200
  const magnitude = Math.pow(10, Math.floor(Math.log10(raw)))
  return Math.max(magnitude, 0.001)
}

/**
 * Guess a slider range from the current value.
 *
 * Crude on purpose. A metadata table with a hand-picked range per field would
 * be nicer and would rot immediately — the point of generating the panel is
 * that config.ts stays the only place a tuning value is described.
 */
function rangeFor(path: string, value: number): [number, number] {
  const override = RANGE_OVERRIDES[path]
  if (override) return override
  if (value === 0) return [0, 1]
  if (value > 0) return [0, value * 4]
  return [value * 4, 0]
}

function formatNumber(value: number): string {
  return Math.abs(value) >= 100 || Number.isInteger(value) ? String(value) : value.toFixed(3).replace(/0+$/, '')
}

export class DebugPanel {
  private readonly panel: HTMLDivElement
  private readonly toggle: HTMLButtonElement
  /** Deep snapshot taken before anything is touched, for reset. */
  private readonly original = structuredClone(config) as unknown as Bag

  constructor() {
    const style = document.createElement('style')
    style.textContent = STYLES
    document.head.appendChild(style)

    this.toggle = document.createElement('button')
    this.toggle.className = 'dbg-toggle'
    this.toggle.textContent = 'debug'
    this.toggle.addEventListener('click', () => {
      this.panel.hidden = !this.panel.hidden
    })
    document.body.appendChild(this.toggle)

    this.panel = document.createElement('div')
    this.panel.className = 'dbg-panel'
    this.panel.hidden = true
    document.body.appendChild(this.panel)

    this.build()
  }

  private build(): void {
    this.panel.replaceChildren(this.actions())

    for (const [key, value] of Object.entries(config as unknown as Bag)) {
      if (typeof value !== 'object' || value === null) continue
      this.panel.appendChild(this.section(key, value as Bag, key))
    }
  }

  private actions(): HTMLElement {
    const row = document.createElement('div')
    row.className = 'dbg-actions'

    const reset = document.createElement('button')
    reset.textContent = 'reset all'
    reset.addEventListener('click', () => {
      Object.assign(config, structuredClone(this.original))
      this.build()
    })

    // The workflow this exists for: tune here, then hand the diff over to be
    // baked into config.ts so it survives a refresh.
    const dump = document.createElement('button')
    dump.textContent = 'log changes'
    dump.addEventListener('click', () => {
      const changes = diff(this.original, config as unknown as Bag, '')
      console.log(Object.keys(changes).length ? changes : 'no changes from defaults')
    })

    row.append(reset, dump)
    return row
  }

  private section(title: string, bag: Bag, path: string): HTMLElement {
    const details = document.createElement('details')
    const summary = document.createElement('summary')
    summary.textContent = title
    details.appendChild(summary)

    const body = document.createElement('div')
    body.className = 'dbg-body'

    for (const [key, value] of Object.entries(bag)) {
      const childPath = `${path}.${key}`
      if (value !== null && typeof value === 'object' && !Array.isArray(value)) {
        body.appendChild(this.section(key, value as Bag, childPath))
      } else {
        const row = this.control(bag, key, childPath, value)
        if (row) body.appendChild(row)
      }
    }

    details.appendChild(body)
    return details
  }

  private control(bag: Bag, key: string, path: string, value: unknown): HTMLElement | null {
    const row = document.createElement('div')
    row.className = 'dbg-row'

    const label = document.createElement('div')
    label.className = 'dbg-label'
    const name = document.createElement('span')
    name.className = NEEDS_RESTART.has(path) ? 'dbg-name restart' : 'dbg-name'
    name.textContent = key
    const readout = document.createElement('span')
    readout.className = 'dbg-value'
    label.append(name, readout)
    row.appendChild(label)

    if (typeof value === 'boolean') {
      const input = document.createElement('input')
      input.type = 'checkbox'
      input.checked = value
      input.addEventListener('change', () => {
        bag[key] = input.checked
      })
      readout.appendChild(input)
      return row
    }

    if (typeof value === 'number') {
      const [min, max] = rangeFor(path, value)
      readout.textContent = formatNumber(value)

      const input = document.createElement('input')
      input.type = 'range'
      input.min = String(min)
      input.max = String(max)
      input.step = String(stepFor(value, min, max))
      input.value = String(value)
      input.addEventListener('input', () => {
        const next = Number(input.value)
        bag[key] = next
        readout.textContent = formatNumber(next)
      })
      row.appendChild(input)
      return row
    }

    if (typeof value === 'string') {
      if (key === 'falloff') {
        const select = document.createElement('select')
        for (const choice of FALLOFF_CHOICES) {
          const option = document.createElement('option')
          option.value = choice
          option.textContent = choice
          select.appendChild(option)
        }
        select.value = value
        select.addEventListener('change', () => {
          bag[key] = select.value
        })
        row.appendChild(select)
        return row
      }

      const input = document.createElement('input')
      input.type = value.startsWith('#') ? 'color' : 'text'
      input.value = value
      input.addEventListener('input', () => {
        bag[key] = input.value
      })
      row.appendChild(input)
      return row
    }

    if (Array.isArray(value)) {
      // Comma-separated rather than a control per element: arrays here are
      // short lists of numbers or ids, and a text field handles both.
      const numeric = value.every((entry) => typeof entry === 'number')
      const input = document.createElement('input')
      input.type = 'text'
      input.value = value.join(', ')
      input.addEventListener('change', () => {
        const parts = input.value
          .split(',')
          .map((part) => part.trim())
          .filter((part) => part.length > 0)
        bag[key] = numeric ? parts.map(Number).filter((n) => !Number.isNaN(n)) : parts
      })
      row.appendChild(input)
      return row
    }

    return null
  }
}

/** Flat map of every leaf that differs from the defaults. */
function diff(before: Bag, after: Bag, prefix: string): Record<string, unknown> {
  const changes: Record<string, unknown> = {}

  for (const [key, next] of Object.entries(after)) {
    const path = prefix ? `${prefix}.${key}` : key
    const previous = before?.[key]

    if (next !== null && typeof next === 'object' && !Array.isArray(next)) {
      Object.assign(changes, diff((previous ?? {}) as Bag, next as Bag, path))
      continue
    }

    const same = Array.isArray(next) ? JSON.stringify(next) === JSON.stringify(previous) : next === previous
    if (!same) changes[path] = next
  }

  return changes
}
